### ISSUE TITLE
Bug introduced by #4709

### ISSUE THREAD

**Issue by guybedford** [rustwasm/wasm-bindgen#4732]
When testing workers-rs against main I was getting this build error:

```
error[E0596]: cannot borrow data in dereference of `Pin<&mut TimeoutFuture>` as mutable
   --> /Users/gbedford/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gloo-timers-0.3.0/src/future.rs:104:31
    |
104 |         Future::poll(Pin::new(&mut self.rx), cx).map(|t| t.unwrap_throw())
    |                               ^^^^^^^^^^^^ cannot borrow as mutable
    |
    = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `Pin<&mut TimeoutFuture>`

error[E0596]: cannot borrow data in dereference of `Pin<&mut IntervalStream>` as mutable
   --> /Users/gbedford/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gloo-timers-0.3.0/src/future.rs:160:36
    |
160 |         Stream::poll_next(Pin::new(&mut self.receiver), cx)
    |                                    ^^^^^^^^^^^^^^^^^^ cannot borrow as mutable
    |
    = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `Pin<&mut IntervalStream>`

```

bisecting the build, shows this is caused by #4709.

We need to make sure to fix or revert before the next release.

**Comment by RReverser** [comment]
Hm are you sure it's #4709? From a quick glance, I don't see how that change to closures could've affected mutability of oneshot receiver.

Is there a minimal repro project I could try?

**Comment by RReverser** [comment]
> Is there a minimal repro project I could try?

Found https://github.com/ranile/gloo/tree/master/examples/clock, trying now. Gloo itself seems somewhat outdated, but hopefully can repro.

**Comment by RReverser** [comment]
You are right, somehow it is #4709...

**Comment by RReverser** [comment]
Oh wow I figured it out, but that's hell of a bug-at-a-distance.
