### ISSUE TITLE
Version v0.2.85 breaks stdweb, possibly due to a breaking change

### ISSUE THREAD

**Issue by CMDJojo** [rustwasm/wasm-bindgen#3415]
### Describe the Bug

Building a project which depends on `stdweb-0.4.20` works fine on `wasm-bindgen-0.2.84` but doesn't on `wasm-bindgen-0.2.85`, it fails with this message:

```
error[E0433]: failed to resolve: unresolved import
  --> /Users/cmdjojo/.cargo/registry/src/github.com-1ecc6299db9ec823/stdweb-0.4.20/src/webcore/ffi/wasm_bindgen.rs:67:32
   |
67 |             alloc: &Closure< Fn( usize ) -> *mut u8 >,
   |                                ^ unresolved import

error[E0425]: cannot find function `wasm_bindgen_initialize` in this scope
  --> /Users/cmdjojo/.cargo/registry/src/github.com-1ecc6299db9ec823/stdweb-0.4.20/src/webcore/ffi/wasm_bindgen.rs:77:22
   |
77 |         let module = wasm_bindgen_initialize( memory, table, &alloc, &free );
   |                      ^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

Some errors have detailed explanations: E0425, E0433.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `stdweb` due to 2 previous errors; 4712 warnings emitted
```

Is it possible that this version could have introduced a breaking change?

### Steps to Reproduce

1. Create a new Cargo project with these dependencies:
```
[dependencies]
wasm-bindgen = "=0.2.85"
stdweb = "0.4.20"
```
2. Build it with `cargo build --target wasm32-unknown-unknown` and see the error:
```
❯ cargo build --target wasm32-unknown-unknown
   Compiling stdweb v0.4.20
error[E0433]: failed to resolve: unresolved import
  --> /Users/cmdjojo/.cargo/registry/src/github.com-1ecc6299db9ec823/stdweb-0.4.20/src/webcore/ffi/wasm_bindgen.rs:67:32
   |
67 |             alloc: &Closure< Fn( usize ) -> *mut u8 >,
   |                                ^ unresolved import

error[E0425]: cannot find function `wasm_bindgen_initialize` in this scope
  --> /Users/cmdjojo/.cargo/registry/src/github.com-1ecc6299db9ec823/stdweb-0.4.20/src/webcore/ffi/wasm_bindgen.rs:77:22
   |
77 |         let module = wasm_bindgen_initialize( memory, table, &alloc, &free );
   |                      ^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
```
4. You clearly see that something is wrong. Now, change the dependencies to say `wasm-bindgen = "=0.2.84"`
5. Build with `cargo build --target wasm32-unknown-unknown` and see that it now builds with the older version of wasm-bindgen.

This is a minimal example showing that `stdweb` breaks on the new update to `wasm-bindgen`. If you want a real-world example of this breaking, see https://github.com/modmark-org/modmark/pull/300 where the build failed due to the update. Feel free to clone [`modmark-org/modmark`](https://github.com/modmark-org/modmark) and do `cd playground && ./build-playground` and see the build fail. Then, change `playground/web_bindings/Cargo.toml` to `wasm-bindgen = "=0.2.84"` and see it succeed.

### Expected Behavior

I would have expected that `0.2.85` wouldn't break `0.2.84` and that everything that compiles under `0.2.84` would also compile under `0.2.85`

### Actual Behavior

`stdweb` doesn't build under `0.2.85`

**Comment by daxpedda** [comment]
This is an issue with the update to `syn` v2, see https://github.com/dtolnay/syn/issues/1451. I'm not sure how this will turn out, but if `syn` considers this to be "working as intended" (which I would understand), then there is nothing we can do about it on our side.

Obviously, this could be fixed by not using bare trait objects in `stdweb`, but unfortunately the project is not maintained anymore.

**Comment by daxpedda** [comment]
[dtolnay](https://github.com/dtolnay) confirmed that this is intentional behavior by `syn` v2: https://github.com/dtolnay/syn/issues/1451#issuecomment-1540995129.

So nothing really can be done about this. Downgrading to `syn` v1 isn't really an option.
