### PR TITLE
Fix Closure interaction with Pin

### LINKED ISSUE #4732: Bug introduced by #4709
When testing workers-rs against main I was getting this build error:

```
error[E0596]: cannot borrow data in dereference of `Pin<&mut TimeoutFuture>` as mutable
   --> /Users/gbedford/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gloo-timers-0.3.0/src/future.rs:104:31
    |
104 |         Future::poll(Pin::new(&mut self.rx), cx).map(|t| t.unwrap_throw())
    |                               ^^^^^^^^^^^^ cannot borrow as mutable
    |
    = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `Pin<&mut TimeoutFuture>`

error[E0596]: cannot borrow data in dereference of `Pin<&mut IntervalStream>` as mutable
   --> /Users/gbedford/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gloo-timers-0.3.0/src/future.rs:160:36
    |
160 |         Stream::poll_next(Pin::new(&mut self.receiver), cx)
    |                                    ^^^^^^^^^^^^^^^^^^ cannot borrow as mutable
    |
    = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `Pin<&mut IntervalStream>`

```

bisecting the build, shows this is caused by #4709.

We need to make sure to fix or revert before the next release.

### PR DESCRIPTION
**Pull request by RReverser**
This is hell of a bug-at-a-distance, and I almost suspect it might be a Rust bug since for all other intents and purposes `Closure<T>` was still considered `Sized` even without this fix.

I'll look into it a bit more, but for now... Fixes #4732.

### CODE REVIEW

**Comment by RReverser** [comment]
> I'll look into it a bit more, but for now...

So far narrowed it down to `dyn Trait` not implementing `Unpin` unless explicitly specified in bounds, but other unsized types and `Box<dyn Trait>` implementing it fine:

```rust
trait MyTrait {}
trait MyTraitWithExplicitUnpin: Unpin {}

const fn assert_unpin<T: ?Sized + Unpin>() {}

const _: () = assert_unpin::<[u8]>(); // OK
const _: () = assert_unpin::<Box<dyn MyTrait>>(); // OK
const _: () = assert_unpin::<dyn MyTraitWithExplicitUnpin>(); // OK
const _: () = assert_unpin::<dyn MyTrait>(); // Error
```

I guess it's not a Rust bug, but just shows again how complicated pinning mechanics are... I need to read up on it a bit more to understand why the restriction applies only to unboxed dyn Trait...
