### ISSUE TITLE
wasm-bindgen does not build without std feature

### ISSUE THREAD

**Issue by josephlr** [rustwasm/wasm-bindgen#1745]
### Describe the Bug

The wasm-bindgen crate has an on-by-default `std` feature, which could be disabled to support `no_std` contexts. However, this doesn't seem to work currently. Encountered when investigating https://github.com/rust-random/getrandom/pull/99 .

### Steps to Reproduce

1. Add `wasm-bindgen = { version = "0.2.50", default-features = false}` in your Cargo.toml
2. Get the following compiler error:

```
error[E0433]: failed to resolve: use of undeclared type or module `mem`
   --> /home/joe/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.48/src/convert/slices.rs:199:9
    |
199 |         mem::transmute::<Box<[u8]>, Box<str>>(<Box<[u8]>>::from_abi(js))
    |         ^^^ use of undeclared type or module `mem`

error[E0433]: failed to resolve: maybe a missing `extern crate anyref;`?
    --> /home/joe/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.48/src/lib.rs:1054:16
     |
1054 |         crate::anyref::link_intrinsics();
     |                ^^^^^^ maybe a missing `extern crate anyref;`?

error[E0412]: cannot find type `Box` in this scope
   --> /home/joe/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.48/src/convert/slices.rs:97:27
    |
97  |               type Anchor = Box<[$t]>;
    |                             ^^^ not found in this scope
...
122 | / vectors! {
123 | |     u8 i8 u16 i16 u32 i32 u64 i64 usize isize f32 f64
124 | | }
    | |_- in this macro invocation

error[E0412]: cannot find type `Box` in this scope
   --> /home/joe/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.48/src/convert/slices.rs:100:54
    |
100 |               unsafe fn ref_from_abi(js: WasmSlice) -> Box<[$t]> {
    |                                                        ^^^ not found in this scope
...
122 | / vectors! {
123 | |     u8 i8 u16 i16 u32 i32 u64 i64 usize isize f32 f64
124 | | }
    | |_- in this macro invocation

error[E0412]: cannot find type `Box` in this scope
   --> /home/joe/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.48/src/convert/slices.rs:101:18
    |
101 |                   <Box<[$t]>>::from_abi(js)
    |                    ^^^ not found in this scope
...
122 | / vectors! {
123 | |     u8 i8 u16 i16 u32 i32 u64 i64 usize isize f32 f64
124 | | }
    | |_- in this macro invocation

error[E0412]: cannot find type `Box` in this scope
   --> /home/joe/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.48/src/convert/slices.rs:195:19
    |
195 |     type Anchor = Box<str>;
    |                   ^^^ not found in this scope

error[E0412]: cannot find type `Box` in this scope
   --> /home/joe/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.48/src/convert/slices.rs:199:26
    |
199 |         mem::transmute::<Box<[u8]>, Box<str>>(<Box<[u8]>>::from_abi(js))
    |                          ^^^ not found in this scope

error[E0412]: cannot find type `Box` in this scope
   --> /home/joe/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.48/src/convert/slices.rs:199:37
    |
199 |         mem::transmute::<Box<[u8]>, Box<str>>(<Box<[u8]>>::from_abi(js))
    |                                     ^^^ not found in this scope

error[E0412]: cannot find type `Box` in this scope
   --> /home/joe/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.48/src/convert/slices.rs:199:48
    |
199 |         mem::transmute::<Box<[u8]>, Box<str>>(<Box<[u8]>>::from_abi(js))
    |                                                ^^^ not found in this scope
```

### Expected Behavior

Either the crate should work without the `std` feature, or the crate should not support `no_std` environments

### Additional Context

Note that the `anyref` error has been present for awhile, but the `Box` errors only appeared in 
 version 0.2.48, most likely caused by #1626.

**Comment by elichai** [comment]
Something really weird has happened. 
I tried fixing the bug on my laptop and it just disappeared. 
not sure what happens but the `no-std` somehow works now. (sadly no VCS over the Cargo.lock to investigate what changed)

**Comment by alexcrichton** [comment]
Thanks for the report! Awhile back it was decided that we aren't going to support this any more since it never really comes up in the wild, so for now the `std` feature is basically required.

**Comment by RReverser** [comment]
Ohh came across this issue while trying to debug the same. @alexcrichton Perhaps worth removing the `feature` then or at least using `compile_error!(...)` to show a more meaningful message when `std` is disabled?

**Comment by alexcrichton** [comment]
Seems reasonable to me to probably just remove it at this point!

**Comment by cdecompilador** [comment]
Maybe instead of having the `std` as feature, having `no_std` as a feature would a good idea, because webassembly was not just designed for the web it's also planned to be used on embeded in the near future. So a way to generate the smallest binary possible may be necessary

**Comment by memoryruins** [comment]
> Maybe instead of having the std as feature, having no_std as a feature would a good idea, 

Features are additive thus must not disable any functionality, which wouldn't work out for a `no_std` feature.
https://doc.rust-lang.org/cargo/reference/features.html#feature-unification
