### ISSUE TITLE
Web worker example fails to build

### ISSUE THREAD

**Issue by mb720** [rustwasm/wasm-bindgen#3256]
### Describe the Bug

The [Wasm in web worker](https://github.com/rustwasm/wasm-bindgen/tree/main/examples/wasm-in-web-worker) examples fails to build when running `./build.sh`:

>error[E0599]: no method named `dyn_ref` found for struct `Element` in the current scope

### Steps to Reproduce

1. `git clone http://github.com/rustwasm/wasm-bindgen.git --depth 1`
2. `cd wasm-bindgen/examples/wasm-in-web-worker`
3. `./build.sh`

### Expected Behavior

I expected the example to compile.

### Actual Behavior

It produced an error, see above.

### Additional Context

* `cargo version`: cargo 1.68.0-nightly (8c460b223 2023-01-04)
* Arch Linux 6.1.6

I was able to build and run the example `wasm_no_modules_js_worker` from [this repo](https://github.com/sgasse/wasm_worker_interaction) by Simon B. Gasse.

**Comment by Liamolucko** [comment]
I can't reproduce this. This sounds like it was caused by #3221, though, since it removed the manual import of `JsCast`, which would have caused such an error if the example was built with a version of `wasm-bindgen` before `JsCast` was added to `wasm_bindgen::prelude`.

Now that 0.2.84 has been released, though, and the example explicitly requires it and thus `JsCast` in `wasm_bindgen::prelude`, I think this should be fixed. Can you confirm whether you still have this problem?

**Comment by mb720** [comment]
I can confirm that the application builds now, thanks.

When serving the website using [`http`](https://crates.io/crates/https) or `python3 -m http.server`, and connecting to `localhost:8000` with a browser, I observe that the following files are fetched in a seemingly endless loop:

  * `worker.js`
  * `wasm_in_web_worker.js`
  * `wasm_in_web_worker_bg.wasm`

Do you see that too?

---

* `cargo version`: cargo 1.68.0-nightly (985d561f0 2023-01-20)
* Arch Linux 6.1.8
* Firefox 109.0.1
* Chromium 109.0.5414.119

**Comment by Liamolucko** [comment]
> When serving the website using [`http`](https://crates.io/crates/https) or `python3 -m http.server`, and connecting to `localhost:8000` with a browser, I observe that the following files are fetched in a seemingly endless loop:
> 
> 
> 
>   * `worker.js`
> 
>   * `wasm_in_web_worker.js`
> 
>   * `wasm_in_web_worker_bg.wasm`

Oh, right. Sorry, that was just fixed in #3278. I think I responded to you right before I merged #3248 and caused that.

**Comment by mb720** [comment]
Thanks for fixing this, Liam! The example works flawlessly now.
